from datetime import datetime
from pathlib import Path
from config import GENERATED_CFG_DIR


def generate_cfg(mode: str, params: dict) -> Path:
    if mode == "OS-SE":
        cfg_text = generate_osse_cfg(params)
        prefix = "osse"
    elif mode == "Tritonia":
        cfg_text = generate_tritonia_cfg(params)
        prefix = "tritonia"
    else:
        raise ValueError(f"未知模式: {mode}")

    filename = datetime.now().strftime(f"{prefix}_%Y%m%d_%H%M%S.cfg")
    cfg_path = GENERATED_CFG_DIR / filename
    cfg_path.write_text(cfg_text, encoding="utf-8")
    return cfg_path


def generate_osse_cfg(params: dict) -> str:
    return f"""\
; =========================
; ATH GUI Generated Config
; Mode: OS-SE
; =========================

Throat.Profile = 1
Throat.Diameter = {params["throat_diameter"]}
Throat.Angle = {params["throat_angle"]}
Coverage.Angle = {params["coverage_angle"]}
Length = {params["length"]}

Term.s = {params["term_s"]}
Term.q = {params["term_q"]}
Term.n = {params["term_n"]}

Mesh.AngularSegments = {params["mesh_angular_segments"]}
Mesh.LengthSegments = {params["mesh_length_segments"]}
Mesh.ThroatResolution = {params["mesh_throat_resolution"]}
Mesh.MouthResolution = {params["mesh_mouth_resolution"]}

Output.STL = 1
Output.ABECProject = 1
"""


def generate_tritonia_cfg(params: dict) -> str:
    return f"""\
; -------------------------------------------------------
; Tritonia Waveguide
; Generated by GUI
; Based on Marcel Batik ATH example
; -------------------------------------------------------

OSSE = {{
  L = {params["L"]}  ; [mm]
  r0 = {params["r0"]}  ; [mm]
  a0 = {params["a0"]}  ; [deg]
  a = {params["a_expr"]}  ; [deg]
  s = {params["s_expr"]}
  n = {params["n"]}
  q = {params["q"]}
  k = {params["k"]}
}}

; Morphing the raw OSSE shape into a rectangle
Morph.TargetShape = {params["morph_target_shape"]}
Morph.FixedPart = {params["morph_fixed_part"]}
Morph.Rate = {params["morph_rate"]}
Morph.CornerRadius = {params["morph_corner_radius"]} ; [mm]

; -------------------------------------------------------
; Mesh Setting
; -------------------------------------------------------

Mesh.AngularSegments = {params["mesh_angular_segments"]}
Mesh.LengthSegments = {params["mesh_length_segments"]}
Mesh.CornerSegments = {params["mesh_corner_segments"]}

Mesh.ThroatResolution = {params["mesh_throat_resolution"]}
Mesh.MouthResolution = {params["mesh_mouth_resolution"]}
Mesh.InterfaceResolution = {params["mesh_interface_resolution"]}

Mesh.SubdomainSlices = {params["mesh_subdomain_slices"]}

; -------------------------------------------------------
; ABEC Project Setting
; -------------------------------------------------------

ABEC.SimType = {params["abec_sim_type"]}
ABEC.f1 = {params["abec_f1"]} ; [Hz]
ABEC.f2 = {params["abec_f2"]} ; [Hz]
ABEC.NumFrequencies = {params["abec_num_frequencies"]}
ABEC.MeshFrequency = {params["abec_mesh_frequency"]} ; [Hz]

ABEC.Polars:SPL_H = {{
  MapAngleRange = 0,90,19
  Distance = {params["distance_h"]} ; [m]
  Offset = {params["offset_h"]} ; [mm]
}}

ABEC.Polars:SPL_V = {{
  MapAngleRange = 0,90,19
  Distance = {params["distance_v"]} ; [m]
  Offset = {params["offset_v"]}
  Inclination = 90
}}

ABEC.Polars:SPL_D = {{
  MapAngleRange = 0,90,19
  Distance = {params["distance_d"]} ; [m]
  Offset = {params["offset_d"]}
  Inclination = {params["inclination_d"]}
}}

Output.ABECProject = {params["output_abec_project"]}
Output.STL = {params["output_stl"]}

Report = {{
  Title = {params["report_title"]}
  PolarData = SPL_H
  NormAngle = {params["report_norm_angle"]}
}}
"""