from datetime import datetime
from pathlib import Path
from config import GENERATED_CFG_DIR


def generate_cfg(mode: str, params: dict) -> Path:
    if mode == "OS-SE":
        cfg_text = generate_osse_cfg(params)
        prefix = "osse"
    elif mode == "Tritonia":
        cfg_text = generate_tritonia_cfg(params)
        prefix = "tritonia"
    elif mode == "Tritonia-M":
        cfg_text = generate_tritonia_m_cfg(params)
        prefix = "tritonia_m"
    else:
        raise ValueError(f"未知模式: {mode}")

    filename = datetime.now().strftime(f"{prefix}_%Y%m%d_%H%M%S.cfg")
    cfg_path = GENERATED_CFG_DIR / filename
    cfg_path.write_text(cfg_text, encoding="utf-8")
    return cfg_path


def generate_osse_cfg(params: dict) -> str:
    return f"""\
; =========================
; ATH GUI Generated Config
; Mode: OS-SE
; =========================

Throat.Profile = 1
Throat.Diameter = {params["throat_diameter"]}
Throat.Angle = {params["throat_angle"]}
Coverage.Angle = {params["coverage_angle"]}
Length = {params["length"]}

Term.s = {params["term_s"]}
Term.q = {params["term_q"]}
Term.n = {params["term_n"]}

Mesh.AngularSegments = {params["mesh_angular_segments"]}
Mesh.LengthSegments = {params["mesh_length_segments"]}
Mesh.ThroatResolution = {params["mesh_throat_resolution"]}
Mesh.MouthResolution = {params["mesh_mouth_resolution"]}

Output.STL = 1
Output.ABECProject = 1
"""


def generate_tritonia_cfg(params: dict) -> str:
    return f"""\
; -------------------------------------------------------
; Tritonia Waveguide
; Generated by GUI
; Based on Marcel Batik ATH example
; -------------------------------------------------------

OSSE = {{
  L = {params["L"]}  ; [mm]
  r0 = {params["r0"]}  ; [mm]
  a0 = {params["a0"]}  ; [deg]
  a = {params["a_expr"]}  ; [deg]
  s = {params["s_expr"]}
  n = {params["n"]}
  q = {params["q"]}
  k = {params["k"]}
}}

Morph.TargetShape = {params["morph_target_shape"]}
Morph.FixedPart = {params["morph_fixed_part"]}
Morph.Rate = {params["morph_rate"]}
Morph.CornerRadius = {params["morph_corner_radius"]} ; [mm]

Mesh.AngularSegments = {params["mesh_angular_segments"]}
Mesh.LengthSegments = {params["mesh_length_segments"]}
Mesh.CornerSegments = {params["mesh_corner_segments"]}

Mesh.ThroatResolution = {params["mesh_throat_resolution"]}
Mesh.MouthResolution = {params["mesh_mouth_resolution"]}
Mesh.InterfaceResolution = {params["mesh_interface_resolution"]}

Mesh.SubdomainSlices = {params["mesh_subdomain_slices"]}

ABEC.SimType = {params["abec_sim_type"]}
ABEC.f1 = {params["abec_f1"]} ; [Hz]
ABEC.f2 = {params["abec_f2"]} ; [Hz]
ABEC.NumFrequencies = {params["abec_num_frequencies"]}
ABEC.MeshFrequency = {params["abec_mesh_frequency"]} ; [Hz]

ABEC.Polars:SPL_H = {{
  MapAngleRange = 0,90,19
  Distance = {params["distance_h"]} ; [m]
  Offset = {params["offset_h"]} ; [mm]
}}

ABEC.Polars:SPL_V = {{
  MapAngleRange = 0,90,19
  Distance = {params["distance_v"]} ; [m]
  Offset = {params["offset_v"]}
  Inclination = 90
}}

ABEC.Polars:SPL_D = {{
  MapAngleRange = 0,90,19
  Distance = {params["distance_d"]} ; [m]
  Offset = {params["offset_d"]}
  Inclination = {params["inclination_d"]}
}}

Output.ABECProject = {params["output_abec_project"]}
Output.STL = {params["output_stl"]}

Report = {{
  Title = {params["report_title"]}
  PolarData = SPL_H
  NormAngle = {params["report_norm_angle"]}
}}
"""


def generate_tritonia_m_cfg(params: dict) -> str:
    subdomain_line = (
        "Mesh.SubdomainSlices ="
        if str(params["mesh_subdomain_slices"]).strip() == ""
        else f'Mesh.SubdomainSlices = {params["mesh_subdomain_slices"]}'
    )

    return f"""\
; -------------------------------------------------------------------------
;   ATH Tritonia-M Waveguide
;   Generated by GUI
;   Based on Marcel Batik ATH script
; -------------------------------------------------------------------------

Scale = {params["scale"]}

Throat.Profile = 1 ; OS-SE
Throat.Diameter = {params["throat_diameter"]} ; [mm]
Throat.Angle = {params["throat_angle"]} ; [deg]
Length = {params["length"]} ; [mm]

Coverage.Angle = {params["coverage_angle_expr"]} ; [deg]
Term.s = {params["term_s_expr"]}
Term.n = {params["term_n"]}
Term.q = {params["term_q"]}

Morph.TargetShape = {params["morph_target_shape"]}
Morph.FixedPart = {params["morph_fixed_part"]}
Morph.Rate = {params["morph_rate"]}
Morph.CornerRadius = {params["morph_corner_radius"]} ; [mm]

Mesh.Enclosure = {{
  Spacing = {params["enclosure_spacing_left"]},{params["enclosure_spacing_top"]},{params["enclosure_spacing_right"]},{params["enclosure_spacing_bottom"]} ; [mm]
  Depth = {params["enclosure_depth"]} ; [mm]
  EdgeRadius = {params["enclosure_edge_radius"]} ; [mm]
  EdgeType = {params["enclosure_edge_type"]}
  FrontResolution = {params["front_resolution_1"]},{params["front_resolution_2"]},{params["front_resolution_3"]},{params["front_resolution_4"]} ; [mm]
  BackResolution = {params["back_resolution_1"]},{params["back_resolution_2"]},{params["back_resolution_3"]},{params["back_resolution_4"]} ; [mm]
  
  LFSource.B = {{
    Radius = {params["lfsource_radius"]} ; [mm]
    Spacing = {params["lfsource_spacing"]} ; [mm]
    DrivingWeight = {params["lfsource_driving_weight"]}
    SID = {params["lfsource_sid"]}
  }}
}}

Mesh.Quadrants = {params["mesh_quadrants"]}
Mesh.VerticalOffset = {params["mesh_vertical_offset"]}

Mesh.AngularSegments = {params["mesh_angular_segments"]}
Mesh.LengthSegments = {params["mesh_length_segments"]}
Mesh.CornerSegments = {params["mesh_corner_segments"]}

Mesh.ThroatResolution = {params["mesh_throat_resolution"]} ; [mm]
Mesh.MouthResolution = {params["mesh_mouth_resolution"]} ; [mm]
Mesh.InterfaceResolution = {params["mesh_interface_resolution"]} ; [mm]

{subdomain_line}

ABEC.SimType = {params["abec_sim_type"]} ; free space
ABEC.f1 = {params["abec_f1"]} ; [Hz]
ABEC.f2 = {params["abec_f2"]} ; [Hz]
ABEC.NumFrequencies = {params["abec_num_frequencies"]}
ABEC.MeshFrequency = {params["abec_mesh_frequency"]} ; [Hz]

ABEC.Polars:SPL_H = {{
  MapAngleRange = 0,180,37  ; [deg]
  Distance = {params["distance_h"]} ; [m]
  NormAngle = {params["norm_angle_h"]} ; [deg]
}}

ABEC.Polars:SPL_V = {{
  MapAngleRange = 0,180,37  ; [deg]
  Distance = {params["distance_v"]} ; [m]
  Inclination = {params["inclination_v"]} ; [deg]
  NormAngle = {params["norm_angle_v"]} ; [deg]
}}

Output.ABECProject = {params["output_abec_project"]}
Output.STL = {params["output_stl"]}

Report = {{
  Title = "{params["report_title"]}"
  PolarData = SPL_H
  PolarDataV = SPL_V
  NormAngle = {params["report_norm_angle"]}
}}
"""